version: "3"

services:
  node1:
    image: chitchat
    restart: always
    ports:
      - "8081:8080"
  node2:
    image: chitchat
    restart: always
    ports:
      - "8082:8080"
  node3:
    image: chitchat
    restart: always
    ports:
      - "8083:8080"

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.142.0/24
