[versions]
google-guava = "33.0.0-jre"
springdoc-openapi = "2.3.0"

[libraries]
# tools
lombok = { module = "org.projectlombok:lombok" }
google-guava = { module = "com.google.guava:guava", version.ref = "google-guava" }
# test
spring-boot-test = { module = "org.springframework.boot:spring-boot-starter-test" }
# web
spring-boot-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-jetty = { module = "org.springframework.boot:spring-boot-starter-jetty" }
springdoc-openapi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc-openapi" }
# db
spring-boot-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
hibernate-dialects = { module = "org.hibernate.orm:hibernate-community-dialects" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc" }
