server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: chitChat
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db.sqlite
logging:
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
